spring.application.name=remnant-life
spring.datasource.url=jdbc:mysql://localhost:3306/remnant_db
spring.datasource.username=root
spring.datasource.password=Db->aaX?UrJvw|K}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=fQ9WMtunIKMK\HKFxln0KZTTgBfV5Ew7O3D60ej8WtM=
logging.level.root=WARN
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR